import os
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, inch
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                 Table, TableStyle, Image, PageBreak)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from io import BytesIO
from app.config import settings

USABLE_WIDTH = 180 * mm
LEFT_MARGIN = 15 * mm
RIGHT_MARGIN = 15 * mm

def _header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.drawString(LEFT_MARGIN, 10*mm, f"Generated by {settings.COMPANY_NAME} on {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    canvas.drawRightString(A4[0] - RIGHT_MARGIN, 10*mm, f"Page {doc.page}")
    canvas.restoreState()

def _company_header(styles):
    elements = []
    logo_img = None
    try:
        logo_path = os.path.join(os.path.dirname(__file__), "..", "static", "img", "logo.png")
        if os.path.exists(logo_path):
            logo_img = Image(logo_path)
            logo_w = 35 * mm
            aspect = logo_img.imageHeight / logo_img.imageWidth
            logo_img.drawWidth = logo_w
            logo_img.drawHeight = logo_w * aspect
    except:
        pass

    right_col = [
        [Paragraph(f"<b>{settings.COMPANY_NAME}</b>", ParagraphStyle("CompanyNameRight", parent=styles["CompanyName"], alignment=TA_RIGHT))],
        [Paragraph(settings.COMPANY_ADDRESS, ParagraphStyle("SmallRight", parent=styles["Small"], alignment=TA_RIGHT))],
        [Paragraph(f"Phone: {settings.COMPANY_PHONE} | Email: {settings.COMPANY_EMAIL}", ParagraphStyle("SmallRight2", parent=styles["Small"], alignment=TA_RIGHT))],
        [Paragraph(f"NTN: {settings.COMPANY_NTN} | STRN: {settings.COMPANY_STRN}", ParagraphStyle("SmallRight3", parent=styles["Small"], alignment=TA_RIGHT))],
    ]

    if logo_img:
        right_table = Table(right_col, colWidths=[135 * mm])
        right_table.setStyle(TableStyle([("LEFTPADDING", (0, 0), (-1, -1), 0), ("RIGHTPADDING", (0, 0), (-1, -1), 0)]))
        header_table = Table([[logo_img, right_table]], colWidths=[45 * mm, 135 * mm])
    else:
        right_table = Table(right_col, colWidths=[180 * mm])
        right_table.setStyle(TableStyle([("LEFTPADDING", (0, 0), (-1, -1), 0), ("RIGHTPADDING", (0, 0), (-1, -1), 0)]))
        header_table = right_table

    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
    ]))
    elements.append(header_table)
    elements.append(Spacer(1, 6*mm))
    return elements

def _build_item_table(items, styles):
    data = [["Item Name", "Qty", "Unit", "Unit Price", "Total"]]
    for item in items:
        data.append([
            item.get("description", ""),
            str(item.get("quantity", 0)),
            item.get("unit", "pcs"),
            f"{item.get('unit_price', 0):,.2f}",
            f"{item.get('total_price', 0):,.2f}"
        ])
    col_widths = [88*mm, 20*mm, 22*mm, 25*mm, 25*mm]
    table = Table(data, colWidths=col_widths, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8f9fa")]),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))
    return table

def _build_summary(subtotal, discount_amount, tax_amount, tax_rate, wht_amount, fed_amount, total_amount, styles):
    data = [
        ["Subtotal:", f"{subtotal:,.2f}"],
    ]
    if discount_amount > 0:
        data.append(["Discount:", f"-{discount_amount:,.2f}"])
    data.append([f"Sales Tax (GST @ {tax_rate:.0f}%):", f"{tax_amount:,.2f}"])
    if wht_amount > 0:
        data.append(["Withholding Tax:", f"-{wht_amount:,.2f}"])
    if fed_amount > 0:
        data.append(["FED:", f"{fed_amount:,.2f}"])
    data.append(["Total:", f"{total_amount:,.2f}"])

    col_widths = [90*mm, 50*mm]
    table = Table(data, colWidths=col_widths)
    style = [
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("LINEABOVE", (0, -1), (-1, -1), 2, colors.black),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
    ]
    if discount_amount > 0:
        style.append(("LINEBELOW", (0, 1), (-1, 1), 0.5, colors.grey))
    table.setStyle(TableStyle(style))
    return table

def _build_client_info(data_rows, styles):
    table = Table(data_rows, colWidths=[30*mm, 140*mm])
    table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    return table

def _tax_footer_note(styles):
    return Paragraph(
        f"This is a computer-generated tax invoice. GST charged at applicable rates as per "
        f"Pakistan Sales Tax Act 1990. For {settings.COMPANY_NAME} - NTN: {settings.COMPANY_NTN}",
        ParagraphStyle("taxnote", parent=styles["Normal"], fontSize=7,
                        textColor=colors.grey, alignment=TA_CENTER)
    )

def generate_invoice_pdf(invoice_data: dict) -> BytesIO:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=15*mm, bottomMargin=20*mm,
                            leftMargin=LEFT_MARGIN, rightMargin=RIGHT_MARGIN)
    styles = getSampleStyleSheet()
    styles["Title"].fontSize = 16
    styles["Title"].alignment = TA_CENTER
    styles["Normal"].fontSize = 9
    styles["Normal"].spaceAfter = 2
    styles.add(ParagraphStyle("CompanyName", parent=styles["Normal"],
                                           fontSize=16, spaceAfter=2))
    styles.add(ParagraphStyle("Small", parent=styles["Normal"],
                                     fontSize=8, spaceAfter=1))

    elements = []
    elements.extend(_company_header(styles))
    elements.append(Spacer(1, 2*mm))

    h2 = ParagraphStyle("h2", parent=styles["Normal"], fontSize=14,
                         alignment=TA_CENTER, spaceAfter=4*mm)
    elements.append(Paragraph(f"<b>TAX INVOICE</b>", h2))
    elements.append(Spacer(1, 2*mm))

    client_info = [
        ["Invoice #:", invoice_data.get("invoice_no", "")],
        ["Date:", invoice_data.get("invoice_date", "")],
        ["Due Date:", invoice_data.get("due_date", "")],
        ["Client:", invoice_data.get("client_name", "")],
    ]
    if invoice_data.get("client_address"):
        client_info.append(["Address:", invoice_data.get("client_address", "")])
    if invoice_data.get("client_ntn"):
        client_info.append(["NTN:", invoice_data.get("client_ntn", "")])
    elements.append(_build_client_info(client_info, styles))
    elements.append(Spacer(1, 4*mm))

    elements.append(_build_item_table(invoice_data.get("items", []), styles))
    elements.append(Spacer(1, 4*mm))

    tax_rate = invoice_data.get("tax_rate", settings.SALES_TAX_RATE)
    elements.append(_build_summary(
        invoice_data.get("subtotal", 0),
        invoice_data.get("discount_amount", 0),
        invoice_data.get("tax_amount", 0),
        tax_rate,
        invoice_data.get("wht_amount", 0),
        invoice_data.get("fed_amount", 0),
        invoice_data.get("total_amount", 0),
        styles
    ))

    if invoice_data.get("terms"):
        elements.append(Spacer(1, 4*mm))
        elements.append(Paragraph("<b>Terms & Conditions:</b>", styles["Normal"]))
        elements.append(Paragraph(invoice_data["terms"], styles["Normal"]))

    if invoice_data.get("notes"):
        elements.append(Spacer(1, 3*mm))
        elements.append(Paragraph("<b>Notes:</b>", styles["Normal"]))
        elements.append(Paragraph(invoice_data["notes"], styles["Normal"]))

    elements.append(Spacer(1, 5*mm))
    elements.append(_tax_footer_note(styles))

    doc.build(elements, onFirstPage=_header_footer, onLaterPages=_header_footer)
    buf.seek(0)
    return buf

def generate_estimate_pdf(estimate_data: dict) -> BytesIO:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=15*mm, bottomMargin=20*mm,
                            leftMargin=LEFT_MARGIN, rightMargin=RIGHT_MARGIN)
    styles = getSampleStyleSheet()
    styles["Title"].fontSize = 16
    styles["Title"].alignment = TA_CENTER
    styles["Normal"].fontSize = 9
    styles["Normal"].spaceAfter = 2
    styles.add(ParagraphStyle("CompanyName", parent=styles["Normal"],
                                           fontSize=16, spaceAfter=2))
    styles.add(ParagraphStyle("Small", parent=styles["Normal"],
                                     fontSize=8, spaceAfter=1))

    elements = []
    elements.extend(_company_header(styles))
    elements.append(Spacer(1, 2*mm))

    h2 = ParagraphStyle("h2", parent=styles["Normal"], fontSize=14,
                         alignment=TA_CENTER, spaceAfter=4*mm)
    elements.append(Paragraph(f"<b>ESTIMATE / QUOTATION</b>", h2))
    elements.append(Spacer(1, 2*mm))

    client_info = [
        ["Estimate #:", estimate_data.get("estimate_no", "")],
        ["Date:", estimate_data.get("estimate_date", "")],
        ["Valid Until:", estimate_data.get("valid_until", "")],
        ["Client:", estimate_data.get("client_name", "")],
    ]
    if estimate_data.get("client_address"):
        client_info.append(["Address:", estimate_data.get("client_address", "")])
    if estimate_data.get("client_ntn"):
        client_info.append(["NTN:", estimate_data.get("client_ntn", "")])
    elements.append(_build_client_info(client_info, styles))
    elements.append(Spacer(1, 4*mm))

    elements.append(_build_item_table(estimate_data.get("items", []), styles))
    elements.append(Spacer(1, 4*mm))

    tax_rate = estimate_data.get("tax_rate", settings.SALES_TAX_RATE)
    elements.append(_build_summary(
        estimate_data.get("subtotal", 0),
        estimate_data.get("discount_amount", 0),
        estimate_data.get("tax_amount", 0),
        tax_rate,
        0, 0,
        estimate_data.get("total_amount", 0),
        styles
    ))

    if estimate_data.get("terms"):
        elements.append(Spacer(1, 4*mm))
        elements.append(Paragraph("<b>Terms & Conditions:</b>", styles["Normal"]))
        for line in estimate_data["terms"].split("\n"):
            elements.append(Paragraph(line.strip(), styles["Normal"]))

    elements.append(Spacer(1, 5*mm))
    elements.append(Paragraph(
        f"This is a computer-generated estimate. Prices are valid for 15 days. "
        f"For {settings.COMPANY_NAME} - NTN: {settings.COMPANY_NTN} | STRN: {settings.COMPANY_STRN}",
        ParagraphStyle("footer", parent=styles["Normal"], fontSize=7,
                        textColor=colors.grey, alignment=TA_CENTER)
    ))

    doc.build(elements, onFirstPage=_header_footer, onLaterPages=_header_footer)
    buf.seek(0)
    return buf
