import os
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, inch
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                 Table, TableStyle, Image, PageBreak)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from io import BytesIO
from app.config import settings

def _header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.drawString(20*mm, 10*mm, f"Generated by {settings.COMPANY_NAME} on {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    canvas.drawRightString(190*mm, 10*mm, f"Page {doc.page}")
    canvas.restoreState()

def _company_header(styles):
    elements = []
    try:
        logo_path = os.path.join(os.path.dirname(__file__), "..", "static", "img", "logo.png")
        if os.path.exists(logo_path):
            logo = Image(logo_path, width=50*mm, height=20*mm)
            elements.append(logo)
    except:
        pass
    elements.append(Paragraph(f"<b>{settings.COMPANY_NAME}</b>", styles["Title"]))
    elements.append(Paragraph(settings.COMPANY_ADDRESS, styles["Normal"]))
    elements.append(Paragraph(f"Phone: {settings.COMPANY_PHONE} | Email: {settings.COMPANY_EMAIL}", styles["Normal"]))
    elements.append(Paragraph(f"NTN: {settings.COMPANY_NTN} | STRN: {settings.COMPANY_STRN}", styles["Normal"]))
    elements.append(Spacer(1, 5*mm))
    return elements

def _build_item_table(items, styles):
    data = [["#", "Description", "Qty", "Unit", "Unit Price", "Tax%", "Tax Amt", "Total"]]
    for i, item in enumerate(items, 1):
        data.append([
            str(i),
            item.get("description", ""),
            str(item.get("quantity", 0)),
            item.get("unit", "pcs"),
            f"{item.get('unit_price', 0):,.2f}",
            f"{item.get('tax_rate', 0)}%",
            f"{item.get('tax_amount', 0):,.2f}",
            f"{item.get('total_price', 0):,.2f}"
        ])
    col_widths = [12*mm, 65*mm, 15*mm, 12*mm, 22*mm, 15*mm, 20*mm, 22*mm]
    table = Table(data, colWidths=col_widths, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ALIGN", (2, 0), (-1, -1), "RIGHT"),
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8f9fa")]),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))
    return table

def _build_summary(subtotal, discount_amount, tax_amount, wht_amount, fed_amount, total_amount, styles):
    data = [
        ["Subtotal:", f"{subtotal:,.2f}"],
    ]
    if discount_amount > 0:
        data.append(["Discount:", f"-{discount_amount:,.2f}"])
    data.append(["Sales Tax (GST):", f"{tax_amount:,.2f}"])
    if wht_amount > 0:
        data.append(["Withholding Tax:", f"-{wht_amount:,.2f}"])
    if fed_amount > 0:
        data.append(["FED:", f"{fed_amount:,.2f}"])
    data.append(["Total:", f"{total_amount:,.2f}"])

    col_widths = [90*mm, 50*mm]
    table = Table(data, colWidths=col_widths)
    style = [
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("LINEABOVE", (0, -1), (-1, -1), 2, colors.black),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
    ]
    if discount_amount > 0:
        style.append(("LINEBELOW", (0, 1), (-1, 1), 0.5, colors.grey))
    table.setStyle(TableStyle(style))
    return table

def generate_invoice_pdf(invoice_data: dict) -> BytesIO:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=15*mm, bottomMargin=20*mm,
                            leftMargin=15*mm, rightMargin=15*mm)
    styles = getSampleStyleSheet()
    styles["Title"].fontSize = 16
    styles["Title"].alignment = TA_CENTER
    styles["Normal"].fontSize = 9
    styles["Normal"].spaceAfter = 2

    elements = []
    elements.extend(_company_header(styles))
    elements.append(Spacer(1, 3*mm))

    h2 = ParagraphStyle("h2", parent=styles["Normal"], fontSize=14,
                         alignment=TA_CENTER, spaceAfter=5*mm)
    elements.append(Paragraph(f"<b>TAX INVOICE</b>", h2))
    elements.append(Spacer(1, 3*mm))

    client_info = [
        ["Invoice #:", invoice_data.get("invoice_no", "")],
        ["Date:", invoice_data.get("invoice_date", "")],
        ["Due Date:", invoice_data.get("due_date", "")],
        ["Client:", invoice_data.get("client_name", "")],
        ["Address:", invoice_data.get("client_address", "")],
        ["NTN:", invoice_data.get("client_ntn", "")],
    ]
    client_table = Table(client_info, colWidths=[30*mm, 120*mm])
    client_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
    ]))
    elements.append(client_table)
    elements.append(Spacer(1, 5*mm))

    elements.append(_build_item_table(invoice_data.get("items", []), styles))
    elements.append(Spacer(1, 5*mm))

    elements.append(Table([[""]], colWidths=[140*mm]))
    elements.append(_build_summary(
        invoice_data.get("subtotal", 0),
        invoice_data.get("discount_amount", 0),
        invoice_data.get("tax_amount", 0),
        invoice_data.get("wht_amount", 0),
        invoice_data.get("fed_amount", 0),
        invoice_data.get("total_amount", 0),
        styles
    ))

    if invoice_data.get("terms"):
        elements.append(Spacer(1, 5*mm))
        elements.append(Paragraph("<b>Terms & Conditions:</b>", styles["Normal"]))
        elements.append(Paragraph(invoice_data["terms"], styles["Normal"]))

    if invoice_data.get("notes"):
        elements.append(Spacer(1, 3*mm))
        elements.append(Paragraph("<b>Notes:</b>", styles["Normal"]))
        elements.append(Paragraph(invoice_data["notes"], styles["Normal"]))

    # Tax compliance note
    elements.append(Spacer(1, 5*mm))
    tax_note_style = ParagraphStyle("taxnote", parent=styles["Normal"], fontSize=7,
                                     textColor=colors.grey, alignment=TA_CENTER)
    elements.append(Paragraph(
        "This is a computer-generated tax invoice. GST charged at applicable rates as per "
        "Pakistan Sales Tax Act 1990. For DATAPOINT Technologies - NTN: XXXXX-XXXXXXX-X",
        tax_note_style
    ))

    doc.build(elements, onFirstPage=_header_footer, onLaterPages=_header_footer)
    buf.seek(0)
    return buf

def generate_estimate_pdf(estimate_data: dict) -> BytesIO:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=15*mm, bottomMargin=20*mm,
                            leftMargin=15*mm, rightMargin=15*mm)
    styles = getSampleStyleSheet()
    styles["Title"].fontSize = 16
    styles["Title"].alignment = TA_CENTER
    styles["Normal"].fontSize = 9

    elements = []
    elements.extend(_company_header(styles))
    elements.append(Spacer(1, 3*mm))

    h2 = ParagraphStyle("h2", parent=styles["Normal"], fontSize=14,
                         alignment=TA_CENTER, spaceAfter=5*mm)
    elements.append(Paragraph(f"<b>ESTIMATE / QUOTATION</b>", h2))
    elements.append(Spacer(1, 3*mm))

    client_info = [
        ["Estimate #:", estimate_data.get("estimate_no", "")],
        ["Date:", estimate_data.get("estimate_date", "")],
        ["Valid Until:", estimate_data.get("valid_until", "")],
        ["Client:", estimate_data.get("client_name", "")],
    ]
    client_table = Table(client_info, colWidths=[30*mm, 120*mm])
    client_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
    ]))
    elements.append(client_table)
    elements.append(Spacer(1, 5*mm))

    elements.append(_build_item_table(estimate_data.get("items", []), styles))
    elements.append(Spacer(1, 5*mm))

    elements.append(_build_summary(
        estimate_data.get("subtotal", 0),
        estimate_data.get("discount_amount", 0),
        estimate_data.get("tax_amount", 0),
        0, 0,
        estimate_data.get("total_amount", 0),
        styles
    ))

    if estimate_data.get("terms"):
        elements.append(Spacer(1, 5*mm))
        elements.append(Paragraph("<b>Terms & Conditions:</b>", styles["Normal"]))
        elements.append(Paragraph(estimate_data["terms"], styles["Normal"]))

    elements.append(Spacer(1, 5*mm))
    elements.append(Paragraph(
        "This is a computer-generated estimate. Prices are valid for 15 days.",
        ParagraphStyle("footer", parent=styles["Normal"], fontSize=7,
                        textColor=colors.grey, alignment=TA_CENTER)
    ))

    doc.build(elements, onFirstPage=_header_footer, onLaterPages=_header_footer)
    buf.seek(0)
    return buf
