---
deployment:
  tasks:
    - export DEPLOYPATH=/home/datapointtechnol/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - export APPPATH=/home/datapointtechnol/app_backend/
    - export PUBLICPATH=/home/datapointtechnol/public_html/
    - /bin/cp -R * $APPPATH
    - /bin/cp -R public/* $PUBLICPATH